-- Extended core schema scaffold (starter)
CREATE TABLE IF NOT EXISTS roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) UNIQUE);
CREATE TABLE IF NOT EXISTS permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) UNIQUE);
CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT UNSIGNED, permission_id BIGINT UNSIGNED, PRIMARY KEY(role_id, permission_id));
CREATE TABLE IF NOT EXISTS settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `group` VARCHAR(80), `key` VARCHAR(120), `value` LONGTEXT, updated_at DATETIME NULL);
CREATE TABLE IF NOT EXISTS admin_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT UNSIGNED, action VARCHAR(190), context JSON NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS backups (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, file_name VARCHAR(255), file_size BIGINT UNSIGNED, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
